changed PresetTextWrap to PresetTextWarp
dotnet/Open-XML-SDK pull request #1448
Opened 2023-06-13 20:31 UTC by tomjebo

2023-06-13 21:47 UTC, mikeebowen requested changes
I think this was generated without the fix for #1444, which is needed before merging.

2023-06-13 21:47 UTC, mikeebowen commented on data/schemas/schemas_openxmlformats_org_drawingml_2006_diagram.json
> +          "PropertyName": "HightScale",
Is this undoing the fix from #1444 ?

2023-06-13 21:47 UTC, mikeebowen commented on generated/DocumentFormat.OpenXml.Linq/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/Linq.NoNamespace.g.cs
> +        /// <item><description>corresponds to the following strongly-typed properties: PropertySet.HightScale.</description></item>
Same question about #1444

2023-06-13 21:47 UTC, mikeebowen commented on generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/schemas_openxmlformats_org_drawingml_2006_diagram.cs
> +        public Int32Value? HightScale
conflict with fix for #1444

2023-06-13 21:47 UTC, mikeebowen commented on generated/DocumentFormat.OpenXml/DocumentFormat.OpenXml.Generator/DocumentFormat.OpenXml.Generator.OpenXmlGenerator/schemas_openxmlformats_org_drawingml_2006_diagram.cs
> +                .AddAttribute("custScaleY", a => a.HightScale)
Conflict with #1444

2023-06-14 04:08 UTC, tomjebo commented
> I think this was generated without the fix for https://github.com/dotnet/Open-XML-SDK/pull/1444, which is needed before merging.

yup, you're right. It's because 1444 didn't get merged on the backend. I'll take care of that and it will fix this when I remerge everything.

2023-06-14 04:24 UTC, tomjebo commented
Ok, HeightScale fix is now included.

2023-06-14 16:39 UTC, mikeebowen approved these changes

2023-06-14 16:42 UTC, tomjebo commented
/azp run

2023-06-23 10:56 UTC, twsouthwick submitted a review, later dismissed
Lgtm - is there a spell check or something we could run over these property names to get them fixed before v3?

2023-06-26 23:36 UTC, tomjebo commented
> Lgtm - is there a spell check or something we could run over these property names to get them fixed before v3?

yeah, we discussed this and we should do it anyway, but the problem is that things like "warp" to "wrap" don't trigger spell checkers. I'll give it a scan anyway.

2023-06-27 01:21 UTC, tomjebo commented
I did a spell check scan on the front end code (non-generated) and found mostly comment spelling issues with only a couple code issues.

2023-06-27 02:24 UTC, twsouthwick submitted a review, later dismissed
LGTM - although there's a merge conflict

2023-06-27 13:24 UTC, twsouthwick commented
@tomjebo you'll need move the branch to the dotnet fork instead of yours until you get the GH actions working

2023-06-27 19:39 UTC, tomjebo commented
> @tomjebo you'll need move the branch to the dotnet fork instead of yours until you get the GH actions working

Ah, ok. I'll move this over to a new dotnet branch.

2023-06-29 17:28 UTC, twsouthwick commented
@tomjebo can this be closed?

2023-06-29 17:32 UTC, closed without merging